# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/rsa.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(847, 515)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(300, 20, 181, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.txt_plain = QtWidgets.QPlainTextEdit(Dialog)
        self.txt_plain.setGeometry(QtCore.QRect(110, 110, 231, 81))
        self.txt_plain.setObjectName("txt_plain")
        self.txt_info = QtWidgets.QPlainTextEdit(Dialog)
        self.txt_info.setGeometry(QtCore.QRect(460, 110, 231, 81))
        self.txt_info.setObjectName("txt_info")
        self.txt_cipher = QtWidgets.QPlainTextEdit(Dialog)
        self.txt_cipher.setGeometry(QtCore.QRect(110, 240, 231, 81))
        self.txt_cipher.setObjectName("txt_cipher")
        self.txt_sig = QtWidgets.QPlainTextEdit(Dialog)
        self.txt_sig.setGeometry(QtCore.QRect(460, 240, 231, 81))
        self.txt_sig.setObjectName("txt_sig")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(36, 110, 51, 20))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(26, 240, 61, 20))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(376, 110, 61, 20))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(390, 240, 61, 16))
        self.label_5.setObjectName("label_5")
        self.btn_en = QtWidgets.QPushButton(Dialog)
        self.btn_en.setGeometry(QtCore.QRect(100, 350, 75, 23))
        self.btn_en.setObjectName("btn_en")
        self.btn_de = QtWidgets.QPushButton(Dialog)
        self.btn_de.setGeometry(QtCore.QRect(250, 350, 75, 23))
        self.btn_de.setObjectName("btn_de")
        self.btn_sig = QtWidgets.QPushButton(Dialog)
        self.btn_sig.setGeometry(QtCore.QRect(450, 360, 75, 23))
        self.btn_sig.setObjectName("btn_sig")
        self.btn_v = QtWidgets.QPushButton(Dialog)
        self.btn_v.setGeometry(QtCore.QRect(630, 360, 75, 23))
        self.btn_v.setObjectName("btn_v")
        self.btn_gen = QtWidgets.QPushButton(Dialog)
        self.btn_gen.setGeometry(QtCore.QRect(490, 30, 101, 23))
        self.btn_gen.setObjectName("btn_gen")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "RSA Cipher"))
        self.label_2.setText(_translate("Dialog", "Plain Text:"))
        self.label_3.setText(_translate("Dialog", "Cipher Text:"))
        self.label_4.setText(_translate("Dialog", "Information"))
        self.label_5.setText(_translate("Dialog", "Signature"))
        self.btn_en.setText(_translate("Dialog", "Encrypt"))
        self.btn_de.setText(_translate("Dialog", "Decrypt"))
        self.btn_sig.setText(_translate("Dialog", "Sign"))
        self.btn_v.setText(_translate("Dialog", "Verify"))
        self.btn_gen.setText(_translate("Dialog", "Generate Keys"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
